baseURL = "https://example.com"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Ummadum Carpooling"
theme = "ummadum"
googleAnalytics = ""

[imaging]
resampleFilter = "box"
quality = 10

[params]
favicon = "/favicon.png"

[params.partner]
link = "#"
logo = "/img/partner.svg"

[languages.en]
weight = 0
languageName = "English"
contentDir = "content/en"

[[languages.en.menu.main]]
url    = "#partner-info"
name   = "How does it work"
weight = 10

[[languages.en.menu.main]]
url    = "#partners"
name   = "Partners"
weight = 20

[[languages.en.menu.main]]
url    = "#faq"
name   = "FAQ"
weight = 30

[languages.it]
weight = 20
contentDir = "content/it/"
languageName = "Italiano"

[[languages.it.menu.main]]
url    = "#partner-info"
name   = "Come funziona"
weight = 10

[[languages.it.menu.main]]
url    = "#partners"
name   = "Partner"
weight = 20

[[languages.it.menu.main]]
url    = "#faq"
name   = "Domande frequenti"
weight = 30

[languages.de]
weight = 10
contentDir = "content/de/"
languageName = "Deutsch"

[[languages.de.menu.main]]
url    = "#partner-info"
name   = "Wie es funktioniert"
weight = 10

[[languages.de.menu.main]]
url    = "#partners"
name   = "Partner"
weight = 20

[[languages.de.menu.main]]
url    = "#faq"
name   = "FAQ"
weight = 30


######################################## FOOTER

[params.footer]
copyright = "NOI AG - Via Volta 13/A, I-39100 Bolzano - VAT No.: 02595720216 - Built by [CodeWorks](https://codeworks.build)"

[languages.en.footer1]
title = "The project"

[[languages.en.menu.footer1]]
url    = "#testing-companies"
name   = "Pilot companies"
weight = 10

[[languages.en.menu.footer1]]
url    = "#shopping-points"
name   = "Shopping points"
weight = 20

[[languages.en.menu.footer1]]
url    = "#steps-tutorial"
name   = "How does it work"
weight = 30

[[languages.en.menu.footer1]]
url    = "#faq"
name   = "FAQ"
weight = 40

[[languages.en.menu.footer1]]
url    = "#partners"
name   = "Become partner"
weight = 40

[languages.it.footer1]
title = "Il progetto"

[[languages.it.menu.footer1]]
url    = "#testing-companies"
name   = "Pilot companies"
weight = 10

[[languages.it.menu.footer1]]
url    = "#community-info"
name   = "Shopping points"
weight = 20

[[languages.it.menu.footer1]]
url    = "#steps-tutorial"
name   = "How does it work"
weight = 30

[[languages.it.menu.footer1]]
url    = "#faq"
name   = "FAQ"
weight = 40

[[languages.it.menu.footer1]]
url    = "#partners"
name   = "Become partner"
weight = 40

[languages.de.footer1]
title = "The project"

[[languages.de.menu.footer1]]
url    = "#testing-companies"
name   = "Pilot companies"
weight = 10

[[languages.de.menu.footer1]]
url    = "#community-info"
name   = "Shopping points"
weight = 20

[[languages.de.menu.footer1]]
url    = "#steps-tutorial"
name   = "How does it work"
weight = 30

[[languages.de.menu.footer1]]
url    = "#faq"
name   = "FAQ"
weight = 40

[[languages.de.menu.footer1]]
url    = "#partners"
name   = "Become partner"
weight = 40

[languages.en.footer2]
title = "Carpooling for"

[[languages.en.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Users"
weight = 10

[[languages.en.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Driver"
weight = 20

[languages.it.footer2]
title = "Carpooling per"

[[languages.it.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Utenti"
weight = 10

[[languages.it.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Autisti"
weight = 20

[languages.de.footer2]
title = "Carpooling für"

[[languages.de.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Benutzer"
weight = 10

[[languages.de.menu.footer2]]
url    = "https://www.ummadum.com/"
name   = "Fahrer"
weight = 20
