name: ci it.bz.carpooling

on: 
  push:
    paths-ignore:
      - "README.md"
      
  pull_request:
    paths-ignore:
      - "README.md"


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: clone into repo
        uses: actions/checkout@v2

      - name: install hugo
        run: sudo apt-get install hugo

      - name: setup hugo
        run: hugo -s src -d ../target
